package com.example.order.adapter.outbound.persistence;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class SagaLogJpaRepositoryIntegrationTest {

    private EntityManagerFactory emf;
    private EntityManager em;

    @BeforeEach
    void setUp() {
        emf = Persistence.createEntityManagerFactory("orderTestPU");
        em = emf.createEntityManager();
    }

    @AfterEach
    void tearDown() {
        if (em != null && em.isOpen()) em.close();
        if (emf != null && emf.isOpen()) emf.close();
    }

    @Test
    void testPersistAndFindById() {
        em.getTransaction().begin();
        SagaLogEntity entity = new SagaLogEntity("ord-1", "ORDER_CREATED", "Order created",
                LocalDateTime.now());
        em.persist(entity);
        em.getTransaction().commit();

        em.clear();
        List<SagaLogEntity> results = em.createQuery(
                "SELECT s FROM SagaLogEntity s WHERE s.orderId = :orderId", SagaLogEntity.class)
                .setParameter("orderId", "ord-1")
                .getResultList();
        assertThat(results).hasSize(1);
        assertThat(results.get(0).getStep()).isEqualTo("ORDER_CREATED");
        assertThat(results.get(0).getDetail()).isEqualTo("Order created");
        assertThat(results.get(0).getId()).isNotNull();
    }

    @Test
    void testAutoGeneratedId() {
        em.getTransaction().begin();
        SagaLogEntity entity = new SagaLogEntity("ord-2", "WMS_ACKED", "WMS accepted",
                LocalDateTime.now());
        em.persist(entity);
        em.getTransaction().commit();

        assertThat(entity.getId()).isNotNull();
        assertThat(entity.getId()).isGreaterThan(0);
    }
}