-- V12__create_order_snapshots.sql
-- Order state snapshots for point-in-time queries
CREATE TABLE order_snapshots (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    VARCHAR(36) NOT NULL,
    status      VARCHAR(32) NOT NULL,
    snapshot    TEXT NOT NULL,
    version     BIGINT NOT NULL,
    reason      VARCHAR(100),
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_snapshots_order_id_created ON order_snapshots(order_id, created_at DESC);
